[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "robomimic"
version = "0.5.0"
description = "robomimic: A Modular Framework for Robot Learning from Demonstration"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Ajay Mandlekar", email = "amandlek@cs.stanford.edu" },
    { name = "Danfei Xu" },
    { name = "Josiah Wong" },
    { name = "Soroush Nasiriany" },
    { name = "Chen Wang" },
    { name = "Matthew Bronars" },
    { name = "Vaibhav Saxena" },
]
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.13.3",
    "h5py",
    "psutil",
    "tqdm",
    "termcolor",
    "tensorboard",
    "tensorboardX",
    "imageio",
    "imageio-ffmpeg",
    "matplotlib",
    "egl_probe>=1.0.1",
    "torch",
    "torchvision",
    "huggingface_hub==0.23.4",
    "transformers==4.41.2",
    "diffusers==0.11.1",
]

[project.optional-dependencies]
robosuite = [
    "robosuite==1.5.1",
    "mujoco==3.3.7",
]
mjx = [
    "robomimic[robosuite]",
    "mujoco-mjx==3.3.7",
    "jax[cuda12]==0.7.2",
]

[project.urls]
Homepage = "https://github.com/ARISE-Initiative/robomimic"

[dependency-groups]
dev = ["pytest"]

[tool.setuptools.packages.find]
include = ["robomimic*"]
